const Model = require('./model')
const {sequelize} = require('../db/main')
const {log, now} = require('../utils.js')
const _ = require('lodash')
const userDB = require('../db/dbUser')
const crypto = require('crypto')